apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: hostpath-sc
  annotations:
    storageclass.kubernetes.io/is-default-class: "true" # Set to true if you want this as the default
provisioner: kubernetes.io/host-path
parameters:
  path: /kubernetes-data-store
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true

